{
  parserClass="com.davidmis.elmplugin.parser.ElmParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Elm"
  psiImplClassSuffix="Impl"
  psiPackage="com.davidmis.elmplugin.psi"
  psiImplPackage="com.davidmis.elmplugin.psi.impl"

  elementTypeHolderClass="com.davidmis.elmplugin.psi.ElmTypes"
  elementTypeClass="com.davidmis.elmplugin.psi.ElmElementType"
  tokenTypeClass="com.davidmis.elmplugin.psi.ElmTokenType"
}

elmFile ::= (declaration|statement|COMMENT|CRLF|WHITESPACE|WAITING)*

declaration ::= IDENTIFIER WHITESPACE? COLON WHITESPACE? type

type ::= IDENTIFIER (WHITESPACE? ARROW WHITESPACE? type)*

statement ::= IDENTIFIER WHITESPACE? EQUALS WHITESPACE? expression

expression ::= if_expression|simple_expression
simple_expression ::= IDENTIFIER|NUMBER
if_expression ::= IF WHITESPACE expression WHITESPACE THEN WHITESPACE expression WHITESPACE ELSE WHITESPACE expression

property ::= (KEY? SEPARATOR VALUE?) | KEY